### ISSUE TITLE
Save snapshots looks quirky in Edge and Chrome

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#727]
Thank you for reporting an issue. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Environment

[ X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[ ] Internet Explorer

[X] Edge

[ ] Safari

[ ] Other

#### Version

Please specify what version you are using: [ 2.6.7]

#### Summary

"Save snapshot" on the project status page looks very weird in Chrome and Edge. Finally looks OK in IE (WTF).
![image](https://user-images.githubusercontent.com/1837390/74527977-5f55d180-4f27-11ea-8a48-468ec074b041.png)

#### Expected / Desired Behavior / Question

Should looks decent in all browsers.

**Comment by tarjeieo** [comment]
Attempting to update https://github.com/niklasvh/html2canvas/releases

**Comment by Remi749** [comment]
Managed to fix some of it.

![image](https://user-images.githubusercontent.com/28678468/75047671-75cfd000-54c7-11ea-90dc-e49ff74ce76d.png)

Left is the old, right is the new with the following changes done to the html2

```js
let ppElement = document.getElementById("pp-projectstatus");
ppElement.style.fontFamily = '"Segoe UI","Segoe UI","Segoe",Tahoma,Helvetica,Arial,Roboto,"Helvetica Neue",sans-serif';
ppElement.style.fontFeatureSettings = "normal";
const canvas = await (window as any).html2canvas(ppElement);
```

it seems like when html2canvas is executed in Chrome/Edge it ignores a bunch of css properties (but IE is fine).

It probably has to do with html2canvas' way of traversing through the DOM in IE compared to Chrome/Edge as everything looks fine in IE.

Everything apart from the values and text coming from lists are still skipped somehow by html2canvas. So this is still a todo.

**Comment by Remi749** [comment]
Branch: https://github.com/Puzzlepart/prosjektportalen/tree/issues/727

I also fixed another problem while tinkering with this. 

When a user scrolls down the ProjectStatus page and takes a snapshot, the snapshot taken is missing information and the floating navigation bar is placed on top of stuff.

I fixed this by adding a scrollToTop functionality, so that when the user presses the "snapshot" button the page is scrolled to the top before taking the snapshot.

**Comment by Remi749** [comment]
Fixed!

Tested in Chrome, Edge and IE, works perfectly across them all.

The issue seems to be that the html2canvas loses css information such as font-family under export. Setting the font-family in the css manually solved this.

Fixed it through css changes instead of js by adding the correct font-family to the corresponding css files instead of overriding this in the export js code.

**Comment by olemp** [comment]
Solved by @Remi749 in #730

**Comment by Remi749** [comment]
Riskmatrix font issues are still present, 

Solution: More css font-families must be set for the various projectstatus fields.

![image](https://user-images.githubusercontent.com/28678468/85106904-5181c700-b20d-11ea-8bd3-808f9216a9be.png)
